### ISSUE TITLE
Track Information Metadata Tag BPM Decimal Value Handling

### ISSUE THREAD

**Issue by jsetton** [thebigmunch/google-music-proto#2]
While trying to upload some songs using the gms tool, I got the following error:
```
Traceback (most recent call last):
  File "/usr/bin/gms", line 11, in <module>
    sys.exit(gms())
  File "/usr/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/google_music_scripts/commands/upload.py", line 144, in upload
    delete_on_success=delete_on_success
  File "/usr/lib/python3.7/site-packages/google_music_scripts/core.py", line 138, in upload_songs
    song, transcode_lossless=transcode_lossless, transcode_lossy=transcode_lossy
  File "/usr/lib/python3.7/site-packages/google_music/clients/musicmanager.py", line 253, in upload
    track_info = mm_calls.Metadata.get_track_info(song)
  File "/usr/lib/python3.7/site-packages/google_music_proto/musicmanager/calls.py", line 244, in get_track_info
    track.beats_per_minute = int(metadata.tags.bpm[0])
ValueError: invalid literal for int() with base 10: '99.77'
```

Looking closer, some of the files, I am trying to upload, have a decimal value as BPM metadata tag. I believe these were populated from the beets import I did prior to the upload attempt. Anyway, I made the below change to resolve my issue. Let me know if you want me to open a PR for this.

```
--- google_music_proto/musicmanager/calls.py.bak    2019-01-08 18:58:00.075394392 -0500
+++ google_music_proto/musicmanager/calls.py   2019-01-08 21:15:42.234677027 -0500
@@ -241,7 +241,7 @@
                        track.album_artist = metadata.tags.albumartist[0]

                if 'bpm' in metadata.tags:
-                       track.beats_per_minute = int(metadata.tags.bpm[0])
+                       track.beats_per_minute = int(metadata.tags.bpm[0].split('.')[0])

                if 'composer' in metadata.tags:
                        track.composer = metadata.tags.composer[0]
```

**Comment by thebigmunch** [comment]
First, fair warning that if these are MP3s with float in TBPM frame, they will be invalid when I add proper validation to my ``audio-metadata`` library as the ID3v2 spec says it must be an integer.

But, other formats don't have that restriction, so this should be changed to handle them. But not like that. It should become ``round(float(metadata.tags.bpm[0]))`` instead. I've made this change locally, so it will be part of the next release.
