### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by droopanu** [thebigmunch/google-music-proto#8]
**Please read the contributing guidelines linked above and delete this message before opening an issue.**

I'm getting the following error while trying to upload a folder:

[2019-10-14 12:13:36] Logging in to Music Manager
[2019-10-14 12:13:37] Logging in to Mobile Client
[2019-10-14 12:13:38] Loading local songs
[2019-10-14 12:13:39] Comparing hashes
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/google_music_scripts/cli.py", line 920, in run
    DISPATCH[command](args)
  File "/usr/local/lib/python3.7/dist-packages/google_music_scripts/commands.py", line 364, in do_upload
    if generate_client_id(song) not in google_client_ids:
  File "/usr/local/lib/python3.7/dist-packages/google_music_proto/musicmanager/utils.py", line 21, in generate_client_id
    song = audio_metadata.load(song)
  File "/usr/local/lib/python3.7/dist-packages/audio_metadata/api.py", line 119, in load
    return parser_cls.load(fileobj)
  File "/usr/local/lib/python3.7/dist-packages/audio_metadata/formats/mp3.py", line 536, in load
    self.streaminfo = MP3StreamInfo.load(self._obj)
  File "/usr/local/lib/python3.7/dist-packages/audio_metadata/formats/mp3.py", line 492, in load
    bitrate = ((audio_size - frames[0]._size) * 8 * frames[0].sample_rate) / num_samples
ZeroDivisionError: division by zero

Most probably one of the mp3 files is broken, but there is no way to figure out which one. 

Would it be possible to add a debugging option to show the file that is being processed so that way I can see what mp3 is broken :)

Cheers,
Liviu

**Comment by thebigmunch** [comment]
I have a test script [here](https://gist.github.com/thebigmunch/c80560c789ce72d46db301e15c265082) that will try to load all the detected audio files in the directory it's run in and print out any it failed to load. If you could post or email any file(s) it finds, that'd be helpful.

**Comment by droopanu** [comment]
Awesome!
It worked, I found the faulty file.

Watch out as it's a big one (300MB).

https://drive.google.com/file/d/1mZbzaXHTnP9wGRd_iQ6Q7pql_qFSNipq/view?usp=sharing

Cheers,
Liviu
